-- 015_add_is_internal_to_trips.sql
-- Marks trips generated by the own dev (excluded from analytics).
-- Non-breaking: column is NOT NULL DEFAULT false, so existing rows upgrade cleanly.

-- Guard schema: verify preconditions hold. We log warnings, not errors,
-- so a partially-migrated DB still progresses.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'trips'
    ) THEN
        RAISE WARNING 'trips table does not exist; skipping 015_add_is_internal_to_trips';
        RETURN;
    END IF;
END$$;

-- Add the flag column. NOT NULL DEFAULT false keeps every existing trip
-- as "real" (which is correct for prod: backfill of dev trips is a
-- separate, intentional decision documented in the spec).
ALTER TABLE trips
    ADD COLUMN IF NOT EXISTS is_internal BOOLEAN NOT NULL DEFAULT false;

-- Partial index: only rows where is_internal = true are stored.
-- Optimises "WHERE is_internal = true" queries without bloating the
-- index size with the overwhelming majority of real (false) trips.
CREATE INDEX IF NOT EXISTS idx_trips_is_internal_true
    ON trips(is_internal) WHERE is_internal = true;

-- Partial index for the common analytics path: "list real trips ordered
-- by created_at DESC". The index is small because is_internal = false
-- is the overwhelming majority of rows (kept out by the predicate).
CREATE INDEX IF NOT EXISTS idx_trips_real_created
    ON trips(created_at DESC) WHERE is_internal = false;
